###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    redis:
        image: 'redis:alpine'
        container_name: kwcms-redis

    mariadb:
        image: 'mariadb:10.1'
        container_name: kwcms-mariadb
        working_dir: /application
        volumes:
            - './application:/application'
            - './mysql:/var/lib/mysql'
        environment:
            - MYSQL_ROOT_PASSWORD=951357456852
            - MYSQL_DATABASE=kwcms
            - MYSQL_USER=kwcms
            - MYSQL_PASSWORD=kwcms654
        ports:
            - '3306:3306'

    postgres:
        image: 'postgres:10.5-alpine'
        container_name: kwcms-postgres
        working_dir: /application
        volumes:
            - './application:/application'
            - './postgres:/var/lib/postgresql'
        environment:
            - POSTGRES_USER=kwcms
            - POSTGRES_PASSWORD=kwcms654
            - POSTGRES_DB=kwcms
        ports:
            - '5432:5432'

    webserver:
        restart: always
        build: phpdocker/nginx
        container_name: kwcms-web
        working_dir: /application
        volumes:
            - './application:/application'
            - './phpdocker/nginx/default.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '20000:80'
            - '20001:81'
            - '20009:89'

    php-fpm7:
        build: phpdocker/php-fpm7
        container_name: kwcms-php7
        working_dir: /application
        volumes:
            - './application:/application'
            - './phpdocker/php-fpm7/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini'

    php-fpm8:
        build: phpdocker/php-fpm8
        container_name: kwcms-php8
        working_dir: /application
        volumes:
            - './application:/application'
            - './phpdocker/php-fpm8/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'

    php-adminer:
        build: phpdocker/php-fpm7
        container_name: kwcms-adminer
        working_dir: /application
        volumes:
            - './adminer:/application'
            - './phpdocker/php-fpm7/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini'
